"""BF16/FP8 GEMM examples for Ascend. Set TILELANG_DEEPGEMM_LOOP_ORDER before import."""

from .api import (
    LOOP_ORDER,
    bf16_bmm,
    bf16_gemm_nn,
    bf16_gemm_nt,
    bf16_gemm_tn,
    bf16_gemm_tt,
    einsum,
    fp8_bmm,
    fp8_einsum,
    fp8_gemm_nn,
    fp8_gemm_nt,
    fp8_gemm_tn,
    fp8_gemm_tt,
    k_grouped_bf16_gemm_tn_contiguous,
    k_grouped_fp8_gemm_nt_contiguous,
    k_grouped_fp8_gemm_tn_contiguous,
    m_grouped_bf16_gemm_nn_contiguous,
    m_grouped_bf16_gemm_nt_contiguous,
    m_grouped_fp8_gemm_nn_contiguous,
    m_grouped_fp8_gemm_nt_contiguous,
)

__all__ = [
    "LOOP_ORDER",
    "bf16_bmm",
    "bf16_gemm_nn",
    "bf16_gemm_nt",
    "bf16_gemm_tn",
    "bf16_gemm_tt",
    "einsum",
    "fp8_bmm",
    "fp8_einsum",
    "fp8_gemm_nn",
    "fp8_gemm_nt",
    "fp8_gemm_tn",
    "fp8_gemm_tt",
    "k_grouped_bf16_gemm_tn_contiguous",
    "k_grouped_fp8_gemm_nt_contiguous",
    "k_grouped_fp8_gemm_tn_contiguous",
    "m_grouped_bf16_gemm_nn_contiguous",
    "m_grouped_bf16_gemm_nt_contiguous",
    "m_grouped_fp8_gemm_nn_contiguous",
    "m_grouped_fp8_gemm_nt_contiguous",
]
